services:
  - type: web
    name: web-fapecafes-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi --chdir backend
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings

