services:
  - type: web
    name: web-fapecafes-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
    plan: free
    region: oregon
